/**
 * XML parsing with the default java platform is overkill for many applications. 
 * To make matters worse, the parsers are not thread-safe, requiring a unique 
 * factory object for each thread. The over-engineered implementation is also 
 * too slow to gracefully handle lots of really short XML strings and generally 
 * makes the assumption that you want to parse a small number of very large XML 
 * character streams.<p/>
 * This package contains a simplistic implementation of XML that eschews the 
 * extra features in a full XML spec. and instead provides the basic 
 * functionality of elements with attributes in a thread-safe manner. Here, the 
 * assumption is that the programmer wants to parse and/or generate XML Strings. 
 * Reading an XML file is as simple as <code>RootElement.parseXML(new FileReader(file))</code> 
 * and the XML is generated by the <code>.toString()</code> methods.
 */

package hall.collin.christopher.xml;
